### PR TITLE
Add handbook section about esbuild-plugin-stimulus

### PR DESCRIPTION
**Pull request by zombiezen**
More info here: https://github.com/zombiezen/esbuild-plugin-stimulus

### CODE REVIEW

**Comment by sstephenson** [comment]
Please add this to the wiki instead: https://github.com/hotwired/stimulus/wiki/Controllers-and-Extensions

Thank you!

**Comment by zombiezen** [comment]
Done. I take it that esbuild is not notable enough at this time to merit mention in the handbook, which is understandable. If that changes down the road, I'd be happy to help with the esbuild support.

FWIW, I did not find the wiki to be super discoverable: there's no direct link from the https://stimulus.hotwire.dev/ site. It's a shame, because it does look like there are some useful links there.

**Comment by sstephenson** [comment]
It's not about notability, we just don't have the expertise or time to maintain instructions for every build system. Hence the wiki! 

You're right that we should add a link to it somewhere on the Stimulus site. Would you mind opening a separate issue on the https://github.com/hotwired/stimulus-site repo?

**Comment by zombiezen** [comment]
Sure! Thanks for the context. 🙂

**Pull request closed without merging**
