### PR TITLE
Support keyboard modifier for click events

### PR DESCRIPTION
**Pull request by shouichi**
This commit adds functionality to accept modifiers for click events, e.g., `ctrl+click->link#open`.

### CODE REVIEW

**Comment by lb-** [comment]
Just a thought, this can be done I think pretty easily with custom action options out of the box today. I am wondering of this would be sufficient for your requirements.

I have validated and the below works really well, it even supports the click shorthand data-action notation nicely.

```js
import { Application } from "@hotwired/stimulus"

const application = Application.start();

application.registerActionOption("alt", ({ event, value }) => value ? event.altKey : !event.altKey);
application.registerActionOption("ctrl", ({ event, value }) => value ? event.ctrlKey : !event.ctrlKey);
application.registerActionOption("meta", ({ event, value }) => value ? event.metaKey : !event.metaKey);
```

```html
<button type="button" data-action="gallery#view!alt gallery#expand:alt">View (using shorthand click action)</button>
<button type="button" data-action="click->gallery#expand:ctrl">View (only activate if ctrl is clicked)</button>
<button type="button" data-action="click->gallery#expand:alt:meta">View (only activate if both alt & meta are pressed)</button>
```

Related links: 

* https://stimulus.hotwired.dev/reference/actions
* https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

**Comment by shouichi** [comment]
Cool! Do you think adding those custom action options to Stimulus itself is sensible? They seem common enough.

**Comment by shouichi** [comment]
Thank you for the tip!

**Comment by lb-** [comment]
Also. Should probably cover `shiftKey` also.

**Comment by dhh** [comment]
Even if this is possible already by custom action options, I think it's considerably nicer to have part of the core package 👍

**Pull request merged**
