### PR TITLE
Fire callbacks when targets are added or removed

### PR DESCRIPTION
**Pull request by Sub-Xaero**
I take no credit for this, Sean Doyle did all the hard work in #367. If Sean no longer wants to commit his time to maintaining this PR, I understand. But it would be a terrible shame for this work to be abandoned at the 11th hour, as this is a piece of functionality I think a lot of Stimulus developers have on their wishlist. 

If all parties are happy for the work he did to still go forward, I'm happy to take this over the line.

### CODE REVIEW

**Comment by dhh** [comment]
Would be happy to see this move forward 👍

**Comment by trsteel88** [comment]
@dhh, I'm keen to start using this feature but it doesn't look like there has been a release since December 2020. Will a new tag be released soon for 2.1?

**Comment by marcoroth** [comment]
@trsteel88 There is a new release planned. In the meantime you can use the latest dev-build in order to make use of this feature today. Swap your Stimulus dependency in your `package.json` with this:

```json
"stimulus": "https://github.com/hotwired/dev-builds/archive/stimulus/353890e.tar.gz"

**Comment by trsteel88** [comment]
Thanks @marcoroth. Do you have a set release cycle documented?

p.s absolutely loving stimulus and turbo links! Great work guys.

**Pull request merged**
