### PR TITLE
A simpler (and slightly faster) method of tokenizing a string

### PR DESCRIPTION
**Pull request by tleish**
A small improvement to https://github.com/hotwired/stimulus/pull/344

### CODE REVIEW

**Comment by tleish** [comment]
Not returns empty array (instead of null) if empty string.

**Review by marcoroth — COMMENTED** [review]
Hey @tleish! Thank you for this pull request. 

This looks good from my side. I compared the two implementations and the new version seems to be slightly faster:
https://jsben.ch/tZW0o

Could you rebase this please to resolve the conflicts?

Thank you!

**Comment by tleish** [comment]
> @marcoroth  wrote
> Could you rebase this please to resolve the conflicts?

done

**Review by marcoroth — APPROVED** [review]
Thank you!

**Pull request merged**
