### PR TITLE
Add part about communicating between controllers

### PR DESCRIPTION
**Pull request by alexander-schranz**
Source: https://github.com/hotwired/stimulus/issues/35#issuecomment-355255358

### CODE REVIEW

**Comment by dhh** [comment]
Amended a bit, but good to have in there.

**Comment by alexander-schranz** [comment]
@dhh Thx for updating and merging. Maybe we should before adding also an example how to use events to communicate between controllers. But I'm not sure how that could look like as events are more general and would trigger multiple controllers but maybe you have an a good example which we could add here to make this more clear.

**Comment by dhh** [comment]
There's a full example here: https://github.com/alexander-schranz/stimulus/blob/30818b93050489975947a5f0b3ad25bee5f047c7/docs/reference/controllers.md#cross-controller-coordination-with-events

Or are you looking for something else?

**Comment by alexander-schranz** [comment]
Thx for the fast response. Now I'm understanding that example but still got another question, how is the `clipboard` related here to `effects` need they be registered on the same element to work. Or how I can tell the `clipboard` which specific `effects` controller/element need to be called for that copy element? Possible maybe over some id in the action?

**Comment by NakajimaTakuya** [comment]
@alexander-schranz 
Firing an event via the dispatch method will cause bubbling in this example, as the setting is set to bubbles: true.
https://github.com/hotwired/stimulus/blob/d0aa5d56131c389b63e02815a10c30578607179e/src/core/controller.ts#L64

Therefore, the position of the effect controller can be anywhere in the ancestor.
Also, if you use a global event, you can make it behave in relation to anywhere in the tree.

**Comment by alexander-schranz** [comment]
@NakajimaTakuya Oh okay so they are not directly connected. Just the bubbling over the DOM or if disabled its a global event. Thank you for the clarification.

**Comment by osadasami** [comment]
Check here how to communicate parent to child, child to parent, mixed controllers and distinct controllers https://github.com/osadasami/code/issues/1

**Pull request merged**
