### PR TITLE
Change `String` to `string` for event type

### PR DESCRIPTION
**Pull request by adrienpoly**
this should fix the CI

### CODE REVIEW

**Comment by dhh** [comment]
Looks like there's still an IE11 error:

Screen Shot 2021-07-01 at 9 16 45 AM

Although I'd also be fine to drop compatibility with IE11.

**Comment by marcoroth** [comment]
The CI started to fail after merging #409. We are probably missing a polyfill for the introduced code.

**Comment by Sub-Xaero** [comment]
I've found the issue, IE11 doesn't like the syntax of the given polyfill. I'll PR a fix.

**Comment by Sub-Xaero** [comment]
C/i passed over on #417 :+1

**Comment by adrienpoly** [comment]
excellent @Sub-Xaero, closing in favor of #417

**Pull request closed without merging**
